services:
  - type: web
    name: smartdebit-api
    runtime: python
    rootDir: .
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn smartdebit_core.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
