# Generated by Django 5.2.7 on 2026-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('low_balance', 'Low Balance')], default='active', max_length=20),
        ),
    ]
